### ISSUE TITLE
Issue with contactsUMI4C terminating on splitUMI4C step. 

### ISSUE THREAD

**Issue by minimolecule** [Pasquali-lab/UMI4Cats#10]
Hi, Thank you for making the UMI4Cats Pipeline! Apologies in advance if this error is caused by my own use of the pipeline. I have managed to digest my genome with DpnII, however the contactsUMI4C part of the pipeline keeps terminating on splitUMI4C with the following error. Do you have any advice on how I can resolve this problem? Thanks again for making this pipeline! All the best, Sunniyat 
 
[2021-11-10 12:20:01] Starting splitUMI4C using:
 > Work directory: UMI4C_IRX3_CRISPR-304755451/FASTQ_Generation_i7_only-484826572/PF382_L001-ds.fad6bdb0503f4b64b7c71c0f112f8ead/ 
 > Cut position: 0 
 > Restriction enzyme: GATC 
 > Number of reads loaded into memory: 1e+09
Error in .normarg_at2(at, x) : 
  some ranges in 'at' are off-limits with respect to their corresponding sequence in
  'x'
In addition: Warning messages:
1: In if (nchar(barcode) > unique(width(reads_fqR1))) { :
  the condition has length > 1 and only the first element will be used
2: In S4Vectors:::V_recycle(end, x, x_what = "end", skeleton_what = "x") :
  'length(x)' is not a multiple of 'NROW(end)'

**Comment by mireia-bioinfo** [comment]
Hi Sunniyat, 

Without a reproducible example is quite difficult to dissect what might have gone wrong and how to solve it... However, from the looks of your error it seems that the reads in your FastQ file have different length. Is this the case? This might be what's causing the function to fail, as UMI4Cats is configured to work with reads that have the same length.

**Comment by minimolecule** [comment]
Hi, You are absolutely correct. Thank you for your advice! I have managed to fix the problem by stopping the automatic trimming by Basespace and downloading full-length FASTQs. Thanks again for making this pipeline, it's absolutely brilliant.

**Comment by mireia-bioinfo** [comment]
Glad to help! :smile:
