### ISSUE TITLE
Plotting UMIs normalised trend across entire domainogram or visible region

### ISSUE THREAD

**Issue by minimolecule** [Pasquali-lab/UMI4Cats#13]
Hi, Thank you for making such a brilliant package to help analyse UMI4C data. This may not be an issue, rather the way I am using the package, so apologies in advance if this is due to my own error.  

I would like to ask if there is a way to force plotting the UMI normalised trendline across the entire visible co-ordinates of the plot? I had a look at the plotUMI4C function for additional arguments to help do this but was unable to identify relevant settings. Any advice you may have would be great. I have an example of the plot to this post to help explain what I mean. Best wishes, Sunniyat 
![Rplot-pdgfrbp1-allsil-v-jurkat](https://github.com/Pasquali-lab/UMI4Cats/assets/94066511/88a68d1c-d901-4972-9f3a-223fb8d4ea23)

**Comment by mireia-bioinfo** [comment]
Hi Sunniyat,

Currently there is no way to automatically zoom to the region that has a normalized trendline. Nonetheless, you can force the plot to zoom in using the `xlim` argument in the plotting function, for example: 

```
plotUMI4C(umi,
    grouping = "condition",
    ylim = c(0, 10),
    xlim = c(149e6, 150e6) # You can edit this to add your zoomed in coordinates
)
```

Sorry for the late response, I hope this was helpful anyways!

Mireia
