### ISSUE TITLE
duplicated normalization in calculating calculateAdaptativeTrend

### ISSUE THREAD

**Issue by YuanlongLiu** [Pasquali-lab/UMI4Cats#4]
Hi,
Thanks for developing this package.

In the _calculateAdaptativeTrend_ function I feel the following line does duplicated normalisation: 
_if (!is.null(assays(umi4c)$norm_mat) & normalized) vector_trend <- vector_trend * assays(umi4c)$norm_mat_

Indeed, when normalized==TRUE, the dgram is already normalised, since vector_trend is computed based on the normalized dgram, so it should not be normalized again.

**Comment by mireia-bioinfo** [comment]
You are totally right! Thank you for letting us know. Will work on fixing this as soon as possible.

**Comment by YuanlongLiu** [comment]
👍 thanks for sharing
