### ISSUE TITLE
Possible confusion

### ISSUE THREAD

**Issue by YuanlongLiu** [Pasquali-lab/UMI4Cats#6]
Hi, in the .singleCounterUMI4C function, the idea of the following code is to retrieve ligations whose readID matches the reps_pos_umis$readID. But rather to match the readID, I feel it should be to match the reps_pos_umis$umi (i.e., the 10 character sequence header). If I am correct, the code could be updated. Thanks!

The original code: final_ligations <- unlist(ligations[names(ligations) %in% unique(reps_pos_umis$readID)])
The psudo code I propose: final_ligations <- unlist(ligations[ligation_umi matches unique(reps_pos_umis$umi)])

**Comment by YuanlongLiu** [comment]
(because multiple readIDs can match to the same umi sequence. When you do ligations[names(ligations) %in% unique(reps_pos_umis$readID)], many ligations that are matched by the umi sequence but not the readID will not be retrieved

**Comment by mireia-bioinfo** [comment]
That behaviour is expected. The goal of using UMIs is that of collapsing reads containing the same exact sequence, as they are likely PCR duplictes. Thus, you will have only one representative read containing a specific UMI, as other reads containing that same UMI are PCR duplicates and need to be removed, as they may bias downstream analyses. 

The current implementation discards reads that have the same UMI and just keeps one of them, as the other ones are likely duplicates.

We did this following the methods published with the UMI-4C method, here: https://www.nature.com/articles/nmeth.3922#Sec33
