### ISSUE TITLE
[BUG] When digesting with a restriction enzyme that cut in position > 0 fragments contain a gap

### ISSUE THREAD

**Issue by LaureTomas** [Pasquali-lab/UMI4Cats#8]
Hello guys!

I'm using your package for analysing our UMI-4C datasets but we're using a different restriction enzyme (HindIII) that cuts in the position +1 of the target sequence.

I use the function digestGenome, with the argument options you specify in the table of section 3.2 Reference genome digestion
of your vignette, as follows: 

```R
library(BSgenome.Hsapiens.UCSC.hg19)
refgen <- BSgenome.Hsapiens.UCSC.hg19

hg19_hindiii <- digestGenome(
  res_enz = "AAGCTT",
  cut_pos = 1,
  name_RE = "HindIII",
  ref_gen = refgen,
  out_path = file.path(tempdir(), "digested_genome/")
)
```

The problem is that the fragments generated by the digestion are not contiguous, they have a missing base between them, i.e. the first fragment finished at position 160006 and the next one starts at 16008, so the base at position 16007 is missing.

```R
GRanges object with 837646 ranges and 1 metadata column:
           seqnames            ranges strand |                     id
              <Rle>         <IRanges>  <Rle> |            <character>
       [1]     chr1           1-16006      * |     fragment_HindIII_1
       [2]     chr1       16008-24570      * |     fragment_HindIII_2
       [3]     chr1       24572-27980      * |     fragment_HindIII_3
```

I know one base it's not a big issue for the analysis, but could you solve this bug?

Thanks so much in advance.

**Comment by mireia-bioinfo** [comment]
Dear Laure, 

First of all, thank you for using UMI4Cats! The issue you mentioned has been fixed both in the development and released version of the package. You'll need to wait a couple of days for the changes to appear in the bioconductor server. Then, you'll need to reinstall the package. You can also install the package from this repository if you need to use it right away:

```
BiocManager::install("Pasquali-lab/UMI4Cats")
```

Thanks!
